name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build-gcc
      run: |
          mkdir build 
          cd build
          export CXX=g++-10
          export CC=gcc-10
          echo /usr/bin/g*
          cmake ..
          make -j `nproc`
          cd ..
          rm -rf build
          
  build-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build-clang
      run: |
          sudo apt-get install -y clang-12 clang++-12
          mkdir build 
          cd build
          export CXX=clang++-12
          export CC=clang-12
          echo /usr/bin/g*
          cmake ..
          make -j `nproc`
          cd ..
          rm -rf build
